name: Build dylib

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build dylib
      run: |
        xcodebuild -project DeviceWare.xcodeproj \
                   -scheme DeviceWare \
                   -configuration Release \
                   -sdk iphoneos \
                   BUILD_DIR=$PWD/build \
                   clean build

    - name: Upload dylib artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeviceWare-dylib
        path: build/Release-iphoneos/libDeviceWare.dylib
