name: Build dylib

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile dylib with clang
        run: |
          SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
          clang -isysroot "$SDK" -arch arm64 -dynamiclib -ObjC DeviceWare.m \
                -o libDeviceWare.dylib \
                -current_version 1.0 -compatibility_version 1.0

      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: DeviceWare-dylib
          path: libDeviceWare.dylib
